### ISSUE TITLE
Difficulties with --docformat=restructuredtext and links

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#223]
Hello,

Thank for this software, it really produce a clear website.

I'm trying to generate documentation from ReST docstrings and I cant make the exemple from the reStructuredText docs work... ([here](https://docutils.sourceforge.io/docs/user/rst/quickref.html#hyperlink-targets))

```
External hyperlinks, like Python_.

.. _Python: http://www.python.org/
```

It outputs everything as plain text, but when I remove the linking part it outputs as normal text.  
Here is the warning I get : `bad docstring: TypeError: sequence item 0: expected str instance, bytes found`

Any help would be much appreciated !

Thanks

**Comment by mthuurne** [comment]
I'll do a more thorough investigation tomorrow, but my first guess is that this is a bug that was introduced in the porting from Python 2 to 3, since Python 2 considered `bytes` to be a string type but Python 3 does not. If that is the case, it should be fairly easy to fix.

**Comment by tristanlatr** [comment]
Thanks,

Here is another error I get when setting only a standalone link as the docstring:

```
bad docstring: RuntimeError: dictionary changed size during iteration
```

**Comment by mthuurne** [comment]
I fixed both issues you found. If you'd like to test the fixes, you can find them in the [20.7.x bugfix branch](https://github.com/twisted/pydoctor/commits/20.7.x):
```
pip install git+https://github.com/twisted/pydoctor.git@20.7.x
```
The ReST support doesn't get as much exposure as epytext support and unfortunately the unit tests are incomplete. If you find more issues, please keep reporting them.

**Comment by tristanlatr** [comment]
Hello, 

Thanks it looks like it's working but I can't make the inline links work

```
`GitHub<https://github.com/mfesiem/msiempy>`_
```

Also the python syntax hightlight doesn't seems to work, do we need to enable it somehow? Well... the HTML class are attributed to the right portion of the Python code but it seems there is no CSS to set a special colour. 

See the docs I'm working on here: https://mfesiem.github.io/docs/test/msiempy/msiempy.html

Thanks for your help

**Comment by mthuurne** [comment]
It seems that the CSS for syntax highlighting was lost in [a big style update in 2015](https://github.com/twisted/pydoctor/commit/620c5070d1ae61d552f6aa542a6b2d9946bd0166). I'll resurrect it.

**Comment by mthuurne** [comment]
The syntax highlighting is back, see #226 for details.

I updated the 20.7.x bugfix branch to include this fix.

**Comment by tristanlatr** [comment]
Thanks a lot @mthuurne 

I've upgraded with `python3 -m pip install git+https://github.com/twisted/pydoctor.git@20.7.x`

But It seems it's still the same version on that branch and the syntax highlighting is not there. 

```
pydoctor --version
20.7.2rc1
```

**Comment by mthuurne** [comment]
Ah sorry, I pushed to the wrong remote. It should be there now.

**Comment by tristanlatr** [comment]
Thanks !

Works like a charm.

**Comment by mthuurne** [comment]
pydoctor 20.7.2, which includes the restructured text and syntax highlighting fixes, has been released on PyPI.

I'm closing this issue now; if you discover more bugs in restructured text support, please open a new issue.
